package com.bowman.autotester;

/**********************************
           imports
 **********************************/

import java.lang.String;
import java.lang.StringBuilder;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.GeneratedValue;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

/**
* Test case group entity
* 
* @author  Petr Rasek
* @version 1.0
* @since   2014-11-01 
*/       
        
@Entity
@Table(name = "TEST_CASE_GROUP")
@SequenceGenerator(name = "TEST_CASE_GROUP_SEQ", allocationSize = 1)
@NamedQueries({
    @NamedQuery(name = "getAllTestCaseGroups", 
                query = "SELECT a FROM TestCaseGroup a ORDER BY a.sTitle"),
    @NamedQuery(name = "getTestCaseGroup",
                query = "SELECT a FROM TestCaseGroup a WHERE a.sTitle = :title")       
})        

public class TestCaseGroup {      
    
    /**********************************
              attributes
    **********************************/ 
    
    @Id 
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TEST_CASE_GROUP_SEQ")
    @Column(name = "ID")
    private int iID;
    
    @Column(name = "TITLE", nullable = false, length = 40, unique = true)
    private String sTitle; 
    
    @Column(name = "APPLICATIONS", nullable = false, length = 100)
    private String sApplications;       
    
    @Column(name = "DESCRIPTION", nullable = false, length = 400)
    private String sDescription;
    
    @Column(name = "DIRECTORY", nullable = false, length = 100, unique = true)
    private String sDirectory;
        
    @Column(name = "CREATE_DATE", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date createDate;
    
    @Column(name = "MODIFY_DATE")
    @Temporal(TemporalType.TIMESTAMP)
    private Date modifyDate;
    
    @Column(name = "NOTE", length = 400)
    private String sNote;
    
    /**********************************
              constructors
    **********************************/ 
    
    public TestCaseGroup() {
        
        this.iID = -1;
        this.sTitle = null;
        this.sApplications = null;
        this.sDescription = null;
        this.sDirectory = null;
        this.createDate = null;
        this.modifyDate = null;
        this.sNote = null;
        
    }
    
    /**
    * table TEST_CASE_GROUP
    * column ID - integer, primary key, autogenerated
    * query getAllTestCaseGroups 
    * query getTestCaseGroup
    * @param sTitle TITLE - varchar(40), not null, unique 
    * @param sApplications APPLICATIONs - varchar(100), not null
    * @param sDescription DESCRIPTION - varchar(400), not null
    * @param sDirectory DIRECTORY - varchar(100), not null, unique
    * @param createDate CREATE_DATE - date
    * @param modifyDate MODIFY_DATE - date
    * @param sNote NOTE - varchar(400)
    */      
    public TestCaseGroup(String sTitle, String sApplications, String sDescription, String sDirectory, 
                         Date createDate, Date modifyDate, String sNote) {
        
        this.sTitle = sTitle;
        this.sApplications = sApplications;
        this.sDescription = sDescription;
        this.sDirectory = sDirectory;
        this.createDate = createDate;
        this.modifyDate = modifyDate;
        this.sNote = sNote;
        
    }
    
    /**********************************
              getters, setters
    **********************************/ 
    
    /**   
    * @return int 
    */
    public int getID() {
        
        return this.iID;
        
    }
    
    /** 
    * @return String 
    */
    public String getTitle() {
        
        return this.sTitle;
        
    }
    
    /**  
    * @param sTitle title
    */    
    public void setTitle(String sTitle) {
        
        this.sTitle = sTitle;
        
    }
    
    /**  
    * @return String
    */
    public String getApplications() {
        
        return this.sApplications;
        
    }
    
    /**  
    * @param sApplications applications
    */    
    public void setApplications(String sApplications) {
        
        this.sApplications = sApplications;
        
    }    
    
    /**  
    * @return String
    */
    public String getDescription() {
        
        return this.sDescription;
        
    }
    
    /**  
    * @param sDescription description
    */    
    public void setDescription(String sDescription) {
        
        this.sDescription = sDescription;
        
    }
    
    /**  
    * @return String
    */
    public String getDirectory() {
        
        return this.sDirectory;
        
    }
    
    /**  
    * @param sDirectory directory
    */    
    public void setDirectory(String sDirectory) {
        
        this.sDirectory = sDirectory;
        
    }    
    
    /**  
    * @return Date
    */
    public Date getCreateDate() {
        
        return this.createDate;
        
    }
    
    /**  
    * @param createDate create date
    */    
    public void setCreateDate(Date createDate) {
        
        this.createDate = createDate;
        
    }    
    
    /**  
    * @return Date
    */
    public Date getModifyDate() {
        
        return this.modifyDate;
        
    }
    
    /**  
    * @param modifyDate modify date
    */    
    public void setModifyDate(Date modifyDate) {
        
        this.modifyDate = modifyDate;
        
    }    
    
    /**  
    * @return String
    */
    public String getNote() {
        
        return this.sNote;
        
    }
    
    /**  
    * @param sNote note
    */    
    public void setNote(String sNote) {
        
        this.sNote = sNote;
        
    }    
    
    /**********************************
              methods
    **********************************/     
    
    /**  
    * @return String 
    */
    @Override
    public String toString() {
        
        StringBuilder sbTestCaseGroup = new StringBuilder();
        sbTestCaseGroup.append("ID:").append(iID);
        sbTestCaseGroup.append("|Title:").append(sTitle);
        sbTestCaseGroup.append("|Applications:").append(sApplications);
        sbTestCaseGroup.append("|Description:").append(sDescription);
        sbTestCaseGroup.append("|Directory:").append(sDirectory);
        sbTestCaseGroup.append("|CreateDate:").append(createDate);
        sbTestCaseGroup.append("|ModifyDate:").append(modifyDate);
        sbTestCaseGroup.append("|Note:").append(sNote);
        
        return sbTestCaseGroup.toString();
        
    } 
}
